<a href="https://colab.research.google.com/github/ektamistry/Computer-Vision/blob/main/Fourier_Transform_ipybn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

a. Obtain twiddle factor matrix


b. To find the DFT and IDFT of [1,2,2,1] using twiddle factor matrix.



c. To compute the DFT using matrix method and FFT function.



d. Observe and comment on execution time required for each of the above method.

In [ ]:
import numpy as np

In [ ]:
x = np.array([1,2,1,2]) # Enter the input seqence.

In [ ]:
# obtain forward transform
X = np.fft.fft(x)  # using built in function from fft pack of numpy obtain the transformed sequence
# fft(fast fourier transform )
print(X)

[ 6.+0.j  0.+0.j -2.+0.j  0.+0.j]


In [ ]:
# Obtain inverse transform
X_i = np.fft.ifft(X) # using built in function from fft pack for inverse transform
print(X_i)

[1.+0.j 2.+0.j 1.+0.j 2.+0.j]


Twiddle factor matrix

$W^{nk}_{N} = e^{\frac{-2\pi nk}{N}}$ for n and k = 0 to N-1

$e^{ix} = cosx-isinx$

In [ ]:
# obtain the above twiddle factor matrix for forward transform

N=4
W= np.zeros((4,4), dtype= complex)
for n in range(0,N):
  for k in range(0,N):
    real= int(np.cos(2*np.pi*n*k/N))
    imaginary= -1*int(np.sin(2*np.pi*n*k/N))
    W[n,k]= complex(real,imaginary)
W

array([[ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  0.-1.j, -1.+0.j,  0.+1.j],
       [ 1.+0.j, -1.+0.j,  1.+0.j, -1.+0.j],
       [ 1.+0.j,  0.+1.j, -1.+0.j,  0.-1.j]])

In [ ]:
# obtain transform without using the builtin function
X1 = np.dot( W, np.transpose(x))
X1

array([ 6.+0.j,  0.+0.j, -2.+0.j,  0.+0.j])

In [ ]:
# obtain the above twiddle factor mtrix for inverse transform
N=4
W_inv= np.zeros((4,4), dtype= complex)
for n in range(0,N):
  for k in range(0,N):
    real= int(np.cos(2*np.pi*n*k/N))
    imaginary= int(np.sin(2*np.pi*n*k/N))
    W_inv[n,k]= complex(real,imaginary)
W_inv

array([[ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  0.+1.j, -1.+0.j,  0.-1.j],
       [ 1.+0.j, -1.+0.j,  1.+0.j, -1.+0.j],
       [ 1.+0.j,  0.-1.j, -1.+0.j,  0.+1.j]])

In [ ]:
# Apply inverse DFT on the transformed sequence X1
X1_i = np.dot( W_inv , X1 )/ N
X1_i

array([1.+0.j, 2.+0.j, 1.+0.j, 2.+0.j])

##Conclusion
1. Obtained forward and inverse transform using builtin function from fft pack of numpy.
2. Obtained the twiddle factor matrix for forward transform and inverse transform.
3. Applied inverse DFT on the transformed sequence using matrix method and FFT function.